# Generated by Django 6.0.2 on 2026-02-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appeal_form',
            new_name='appeal',
        ),
    ]
