# Generated by Django 6.0.2 on 2026-02-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_rename_appeal_form_appeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='date',
        ),
    ]
