# Generated by Django 6.0.2 on 2026-02-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_remove_appeal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='emails',
            new_name='email',
        ),
    ]
