# Generated by Django 6.0.2 on 2026-02-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_rename_emails_appeal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='dob',
        ),
        migrations.AddField(
            model_name='appeal',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
