# Generated by Django 6.0.2 on 2026-02-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0005_remove_appeal_dob_appeal_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='password',
        ),
    ]
